Cleanup formatting.
bzr-revno: 121.1.3

diff --git a/helpers/common b/helpers/common
--- a/helpers/common
+++ b/helpers/common
@@ -245,14 +245,14 @@ human2bytes() {
 }
 
 getsize() {
-	local target="$1"
-	if [ -b "$target" ]; then
-		_RET=$(blockdev --getsize64 "$target")
-	elif [ -f "$target" ]; then
-		_RET=$(stat "--format=%s" "$target")
-	else
-		return 1;
-	fi
+    local target="$1"
+    if [ -b "$target" ]; then
+        _RET=$(blockdev --getsize64 "$target")
+    elif [ -f "$target" ]; then
+        _RET=$(stat "--format=%s" "$target")
+    else
+        return 1;
+    fi
 }
 
 is_md() {
@@ -263,23 +263,23 @@ is_md() {
 }
 
 install_grub() {
-	local long_opts="uefi"
-	local getopt_out=$(getopt --name "${0##*/}" \
-		--options "" --long "${long_opts}" -- "$@") &&
-		eval set -- "${getopt_out}"
+    local long_opts="uefi"
+    local getopt_out=$(getopt --name "${0##*/}" \
+        --options "" --long "${long_opts}" -- "$@") &&
+        eval set -- "${getopt_out}"
 
-	local uefi=0
+    local uefi=0
 
-	while [ $# -ne 0 ]; do
-		cur="$1"; next="$2";
-		case "$cur" in
-			--uefi) uefi=$((${uefi}+1));;
-			--) shift; break;;
-		esac
-		shift;
-	done
+    while [ $# -ne 0 ]; do
+        cur="$1"; next="$2";
+        case "$cur" in
+            --uefi) uefi=$((${uefi}+1));;
+            --) shift; break;;
+        esac
+        shift;
+    done
 
-	[ $# -lt 2 ] && { grub_install_usage "must provide mount-point and target-dev" 1>&2; return 1; }
+    [ $# -lt 2 ] && { grub_install_usage "must provide mount-point and target-dev" 1>&2; return 1; }
 
     local mp="$1"
     local cmdline tmp r=""
@@ -409,28 +409,28 @@ install_grub() {
     grubdevs=( "${grubdevs_new[@]}" )
 
     if [ "$uefi" -ge 1 ]; then
-    	debug 1 "installing ${grub_name} to: /boot/efi"
-    	chroot "$mp" env DEBIAN_FRONTEND=noninteractive sh -ec '
-	        prober="/etc/grub.d/30_os-prober"
-	        [ -x $prober ] && chmod -x "$prober"
-	        dpkg-reconfigure "$1"
-	        [ -f $prober ] && chmod +x "$prober"
-	        grub-install --target=$2 --efi-directory=/boot/efi --bootloader-id=ubuntu --recheck || exit; done' \
-	        -- "${grub_name}" "${grub_target}" </dev/null ||
-	        { error "failed to install grub!"; return 1; }
+        debug 1 "installing ${grub_name} to: /boot/efi"
+        chroot "$mp" env DEBIAN_FRONTEND=noninteractive sh -ec '
+            prober="/etc/grub.d/30_os-prober"
+            [ -x $prober ] && chmod -x "$prober"
+            dpkg-reconfigure "$1"
+            [ -f $prober ] && chmod +x "$prober"
+            grub-install --target=$2 --efi-directory=/boot/efi --bootloader-id=ubuntu --recheck || exit; done' \
+            -- "${grub_name}" "${grub_target}" </dev/null ||
+            { error "failed to install grub!"; return 1; }
     else
-	    debug 1 "installing grub-pc to: ${grubdevs[*]}"
-	    chroot "$mp" env DEBIAN_FRONTEND=noninteractive sh -ec '
-	        prober="/etc/grub.d/30_os-prober"
-	        [ -x $prober ] && chmod -x "$prober"
-	        dpkg-reconfigure grub-pc
-	        [ -f $prober ] && chmod +x "$prober"
-	        for d in "$@"; do grub-install "$d" || exit; done' \
-	        -- "${grubdevs[@]}" </dev/null ||
-	        { error "failed to install grub!"; return 1; }
-	fi
+        debug 1 "installing grub-pc to: ${grubdevs[*]}"
+        chroot "$mp" env DEBIAN_FRONTEND=noninteractive sh -ec '
+            prober="/etc/grub.d/30_os-prober"
+            [ -x $prober ] && chmod -x "$prober"
+            dpkg-reconfigure grub-pc
+            [ -f $prober ] && chmod +x "$prober"
+            for d in "$@"; do grub-install "$d" || exit; done' \
+            -- "${grubdevs[@]}" </dev/null ||
+            { error "failed to install grub!"; return 1; }
+    fi
 
-	[ -n "$mp_efi" ] && umount "$mp_efi"
+    [ -n "$mp_efi" ] && umount "$mp_efi"
 }
 
 # vi: ts=4 expandtab syntax=sh
