add support for partitioning a ppc prep disk
bzr-revno: 144.1.1

diff --git a/helpers/common b/helpers/common
--- a/helpers/common
+++ b/helpers/common
@@ -12,7 +12,7 @@ Usage: ${0##*/} [ options ] target-dev
    destroy any partition table that might be there already.
 
    options:
-     -f | --format F   use partition table format F. [mbr, gpt, uefi]
+     -f | --format F   use partition table format F. [mbr, gpt, uefi, prep]
                        default gpt
      -E | --end E      end the partition at E (unit 1k bytes)
      -b | --boot       create a boot partition (512 MiB - default)
@@ -198,6 +198,35 @@ pt_mbr() {
     }
 }
 
+pt_prep() {
+    local target="$1" end=${2:-""}
+    local cmd="" isblk=false
+    [ -b "$target" ] && isblk=true
+
+    sgdisk "$target" --zap-all "$target" ||
+        fail "failed to clear $target";
+
+    cmd=(
+        sgdisk "$target"
+           --new "1::+8M"  --typecode=1:4100
+           --new "2::$end" --typecode=1:8300
+           "$target"
+    )
+    "${cmd[@]}" ||
+        fail "Failed to create GPT partitions (${cmd[*]})"
+
+    if $isblk; then
+        blockdev --rereadpt "$target"
+        udevadm settle
+        [ -b "${target}1" ] ||
+            { error "no partition found ${target}1"; return 1; }
+        [ -b "${target}2" ] ||
+            { error "no partition found ${target}2"; return 1; }
+    fi
+
+    return 0
+}
+
 partition_main() {
     local short_opts="hE:f:bv"
     local long_opts="help,end:,format:,boot,verbose"
@@ -231,7 +260,8 @@ partition_main() {
         end="$_RET"
     fi
 
-    [ "$format" = "gpt" -o "$format" = "mbr" -o "$format" = "uefi" ] ||
+    [ "$format" = "gpt" -o "$format" = "mbr" -o ] ||
+        [ "$format" = "uefi" -o "$format" = "prep" ] ||
         { partition_main_usage "invalid format: $format" 1>&2; return 1; }
 
     TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") ||
@@ -250,6 +280,8 @@ partition_main() {
         pt_gpt "$target" "$end" "$boot"
     elif [ "$format" = "uefi" ]; then
         pt_uefi "$target" "$end"
+    elif [ "$format" = "prep" ]; then
+        pt_prep "$target" "$end"
     fi
 
     trap cleanup EXIT
