Added /boot partition support to UEFI.
bzr-revno: 138.1.10

diff --git a/helpers/common b/helpers/common
--- a/helpers/common
+++ b/helpers/common
@@ -15,7 +15,7 @@ Usage: ${0##*/} [ options ] target-dev
      -f | --format F   use partition table format F. [mbr, gpt, uefi]
                        default gpt
      -E | --end E      end the partition at E (unit 1k bytes)
-     -b | --boot       create a 512MiB (default size) boot partition
+     -b | --boot B     create a boot partition with size B (MiB)
 EOF
     [ $# -eq 0 ] || echo "$@"
 }
@@ -62,7 +62,7 @@ wipedev() {
 
 pt_gpt() {
     local target="$1" end=${2:-""} boot="$3" size="" s512="" ptype="L"
-    local start="2048" rootsize="" bootsize="1048576" maxend=""
+    local start="2048" rootsize="" bootsize="" maxend=""
     local isblk=false
     getsize "$target" ||
         { error "failed to get size of $target"; return 1; }
@@ -72,9 +72,10 @@ pt_gpt() {
     else
         end=$(($end/512))
     fi
-    # 512MiB = 536870912 bytes / 512 bytes per sector = 1048576 sectors
-    # This is currently the default size we have for the /boot partition
-    if [ "$boot" -ge 1 ]; then
+
+    if [ "$boot" -ge 0 ]; then
+        # 2048 sectors per MiB (start=2048)
+        bootsize=$(($boot * $start))
         maxend=$((($size/512)-$start-$bootsize))
         if [ $maxend -lt 0 ]; then
             error "Disk is not big enough for /boot partition on $target";
@@ -88,16 +89,16 @@ pt_gpt() {
 
     [ -b "$target" ] && isblk=true
 
-    if [ "$boot" -ge 1 ]; then 
+    if [ "$boot" -ge 0 ]; then 
         # Creating 'efi', '/boot' and '/' partitions
         sgdisk --new "15:$start:+1M" --typecode=15:ef02 \
-            --new "1:+1M:+513M" --typecode=1:8300 \
-            --new "2::$end"     --typecode=2:8300 "$target" ||
+            --new "1::+$bootM" --typecode=1:8300 \
+            --new "2::$end" --typecode=2:8300 "$target" ||
             { error "failed to gpt partition $target"; return 1; }
     else
         # Creating 'efi' and '/' partitions 
-        sgdisk --new "15:2048:+1M" --typecode=15:ef02 \
-               --new "1::$end"     --typecode=1:8300 "$target" ||
+        sgdisk --new "15:$start:+1M" --typecode=15:ef02 \
+               --new "1::$end" --typecode=1:8300 "$target" ||
             { error "failed to gpt partition $target"; return 1; }
     fi
 
@@ -108,7 +109,7 @@ pt_gpt() {
             { error "no partition found ${target}1"; return 1; }
         [ -b "${target}15" ] ||
             { error "no partition found ${target}15"; return 1; }
-        if [ "$boot" -ge 1 ]; then
+        if [ "$boot" -ge 0 ]; then
             [ -b "${target}2" ] ||
                 { error "no partition found ${target}2"; return 1; }
         fi
@@ -116,8 +117,8 @@ pt_gpt() {
 }
 
 pt_uefi() {
-    local target="$1" end=${2:-""} size="" s512="" ptype="L"
-    local start="2048" pt1size="" maxend=""
+    local target="$1" end=${2:-""} boot="$3" size="" s512="" ptype="L"
+    local start="2048" rootsize="" bootsize="1048576" maxend=""
     local isblk=false
     getsize "$target" ||
         { error "failed to get size of $target"; return 1; }
@@ -127,16 +128,35 @@ pt_uefi() {
     else
         end=$(($end/512))
     fi
-    maxend=$((($size/512)-2048))
+
+    if [ "$boot" -ge 0 ]; then
+        # 2048 sectors per MiB (start=2048)
+        bootsize=$(($boot * $start))
+        maxend=$((($size/512)-$start-$bootsize))
+        if [ $maxend -lt 0 ]; then
+            error "Disk is not big enough for /boot partition on $target";
+            return 1;
+        fi
+    else
+        maxend=$((($size/512)-$start))
+    fi
     [ "$end" -gt "$maxend" ] && end="$maxend"
     debug 1 "maxend=$maxend end=$end size=$size"
 
     [ -b "$target" ] && isblk=true
 
-    # Part 15 is the UEFI partition, part 1 is root
-    sgdisk --new "15:2048:+512M" --typecode=15:ef00 "$target" \
-           --new "1::$end" --typecode=1:8300 "$target" ||
-        { error "failed to sgdisk for uefi to $target"; return 1; }
+    if [ "$boot" -ge 0 ]; then 
+        # Creating 'UEFI', '/boot' and '/' partitions
+        sgdisk --new "15:$start:+512M" --typecode=15:ef00 \
+            --new "1::+$bootM" --typecode=1:8300 \
+            --new "2::$end" --typecode=2:8300 "$target" ||
+            { error "failed to sgdisk for uefi to $target"; return 1; }
+    else
+        # Creating 'UEFI' and '/' partitions 
+        sgdisk --new "15:2048:+512M" --typecode=15:ef00 \
+               --new "1::$end" --typecode=1:8300 "$target" ||
+            { error "failed to sgdisk for uefi to $target"; return 1; }
+    fi
 
     if $isblk; then
         blockdev --rereadpt "$target"
@@ -145,6 +165,10 @@ pt_uefi() {
             { error "no partition found ${target}1"; return 1; }
         [ -b "${target}15" ] ||
             { error "no partition found ${target}15"; return 1; }
+        if [ "$boot" -ge 0 ]; then
+            [ -b "${target}2" ] ||
+                { error "no partition found ${target}2"; return 1; }
+        fi
     fi
 
     mkfs -t vfat -F 32 -n uefi-boot ${target}15 ||
@@ -199,15 +223,15 @@ pt_mbr() {
 }
 
 partition_main() {
-    local short_opts="hE:f:bv"
-    local long_opts="help,end:,format:,boot,verbose"
+    local short_opts="hE:f:b:v"
+    local long_opts="help,end:,format:,boot:,verbose"
     local getopt_out=$(getopt --name "${0##*/}" \
         --options "${short_opts}" --long "${long_opts}" -- "$@") &&
         eval set -- "${getopt_out}" ||
         { partition_main_usage 1>&2; return 1; }
 
     local cur="" next=""
-    local format="gpt" boot=0 target="" end=""
+    local format="gpt" boot="" target="" end=""
 
     while [ $# -ne 0 ]; do
         cur="$1"; next="$2";
@@ -215,7 +239,7 @@ partition_main() {
             -h|--help) partition_main_usage ; exit 0;;
             -E|--end) end=$next; shift;;
             -f|--format) format=$next; shift;;
-            -b|--boot) boot=$((${boot}+1));;
+            -b|--boot) boot=$next; shift;;
             -v|--verbose) VERBOSITY=$((${VERBOSITY}+1));;
             --) shift; break;;
         esac
@@ -249,7 +273,7 @@ partition_main() {
     elif [ "$format" = "gpt" ]; then
         pt_gpt "$target" "$end" "$boot"
     elif [ "$format" = "uefi" ]; then
-        pt_uefi "$target" "$end"
+        pt_uefi "$target" "$end" "$boot"
     fi
 
     trap cleanup EXIT
