helpers/common: wipe_dev / wipe_partitions support --full
wipe_partitions and wipe_dev can now take first argument
of a '--full' to wipe the whole thing, not just the front/end.

this can be necessary for PReP, as I've seen grub complain
on install that the PReP partition was not empty.

So, we zero the whole PReP partition.

bzr-revno: 219.1.10

diff --git a/helpers/common b/helpers/common
--- a/helpers/common
+++ b/helpers/common
@@ -48,22 +48,32 @@ cleanup() {
 
 wipe_partitions() {
     # wipe_partition(blockdev, ptno)
-    local dev="$1" target="" ret="" part=""
+    local dev="" target="" ret="" part="" full="" out=""
+    if [ "$1" = "--full" ]; then
+        full="--full"
+        shift
+    fi
+    dev="$1"
     shift
     for part in "$@"; do
         find_partno "$dev" $part ||
             { ret=$?; error "did not find $part on $dev"; return $ret; }
         target="$_RET"
-        wipedev "$target" false false ||
+        wipedev $full "$target" false false ||
             { ret=$?; error "failed to wipe $part on $dev"; return $ret; }
     done
     return 0
 }
 
 wipedev() {
-    # wipedev(target, wipe_end=true, reread=true)
+    # wipedev([--full,] target, wipe_end=true, reread=true)
     # wipe the front and optionally end of $target
     # if reread=true call rereadpt and settle
+    local full="0"
+    if [ "$1" = "--full" ]; then
+        full="1"
+        shfit
+    fi
     local target="$1" wipe_end=${2:-true} rereadpt=${3:-true}
     local size="" out="" bs="" count="" seek="" mb=$((1024*1024))
     local info=""
@@ -78,30 +88,41 @@ wipedev() {
     if [ "$bs" = "1" ]; then
         error "WARN: odd sized '$target' ($size). not divisible by 512."
     fi
-    [ "$size" -ge "$mb" ] && count=$((mb / bs)) || count=$((size / bs))
 
-    info="size=$size count=$count bs=$bs"
-    debug 1 "wiping start of '$target' with ${info}."
-    # wipe the first MB (up to 'size')
-    out=$(dd if=/dev/zero conv=notrunc "of=$target" \
-            "bs=$bs" "count=$count" 2>&1) || {
-        error "wiping start of '$target' failed."
-        error "  size=$size count=$count bs=$bs: $out"
-        return 1
-    }
+    if [ "$full" != "0" ]; then
+        count=$((size / bs))
+        info="size=$size conv=notrunc count=$count bs=$bs"
+        debug 1 "wiping full '$target' with ${info}."
+        out=$(dd if=/dev/zero conv=notrunc bs=$bs "of=$target" 2>&1) || {
+            error "wiping entire '$target' with ${info} failed."
+            error "$out"
+            return 1
+        }
+    else
+        [ "$size" -ge "$mb" ] && count=$((mb / bs)) || count=$((size / bs))
+        info="size=$size count=$count bs=$bs"
+        debug 1 "wiping start of '$target' with ${info}."
+        # wipe the first MB (up to 'size')
+        out=$(dd if=/dev/zero conv=notrunc "of=$target" \
+                "bs=$bs" "count=$count" 2>&1) || {
+            error "wiping start of '$target' failed."
+            error "  size=$size count=$count bs=$bs: $out"
+            return 1
+        }
 
-    if $wipe_end && [ "$size" -gt "$mb" ]; then
-        # do the last 1MB
-        count=$((mb / bs))
-        seek=$(((size / bs) - $count))
-        info="size=$size count=$count bs=$bs seek=$seek"
-        debug 1 "wiping end of '$target' with ${info}."
-        out=$(dd if=/dev/zero conv=notrunc "of=$target" "seek=$seek" \
-            "bs=$bs" "count=$count" 2>&1)
-        if [ $? -ne 0 ]; then
-            error "wiping end of '$target' failed."
-            error "  size=$size count=$count seek=$seek bs=$bs: $out";
-            return 1;
+        if $wipe_end && [ "$size" -gt "$mb" ]; then
+            # do the last 1MB
+            count=$((mb / bs))
+            seek=$(((size / bs) - $count))
+            info="size=$size count=$count bs=$bs seek=$seek"
+            debug 1 "wiping end of '$target' with ${info}."
+            out=$(dd if=/dev/zero conv=notrunc "of=$target" "seek=$seek" \
+                "bs=$bs" "count=$count" 2>&1)
+            if [ $? -ne 0 ]; then
+                error "wiping end of '$target' failed."
+                error "  size=$size count=$count seek=$seek bs=$bs: $out";
+                return 1;
+            fi
         fi
     fi
 
@@ -340,7 +361,10 @@ pt_prep() {
         udevadm settle
         assert_partitions "$target" 1 2 ||
             { error "$target missing partitions: $_RET"; return 1; }
-        wipe_partitions "$target" 1 2 ||
+        # wipe the full prep partition
+        wipe_partitions --full "$target" 1 ||
+            { error "$target: failed to wipe partitions"; return 1;}
+        wipe_partitions "$target" 2 ||
             { error "$target: failed to wipe partitions"; return 1;}
     fi
 
