helpers/common: remove tabs
the ':vi' indicates that this should be 'expandtab',
so tabs are just wrong here.

bzr-revno: 122

diff --git a/helpers/common b/helpers/common
--- a/helpers/common
+++ b/helpers/common
@@ -5,7 +5,7 @@ error() { echo "$@" 1>&1; }
 debug() { [ ${VERBOSITY:-0} -lt "$1" ] || error "$@"; }
 
 partition_main_usage() {
-	cat <<EOF
+    cat <<EOF
 Usage: ${0##*/} [ options ] target-dev
 
    partition target-dev with a single partition
@@ -26,24 +26,24 @@ cleanup() {
 }
 
 wipedev() {
-	# wipe the front and end (gpt is at end also)
-	local target="$1" size="" out=""
-	getsize "$target" ||
-		{ error "failed to get size of $target"; return 1; }
-	size="$_RET"
-	
-	dd if=/dev/zero conv=notrunc of="$target" \
-		bs=$((1024*1024)) count=1 >/dev/null 2>&1 ||
-		{ error "failed to zero beginning of $target"; return 1; }
+    # wipe the front and end (gpt is at end also)
+    local target="$1" size="" out=""
+    getsize "$target" ||
+        { error "failed to get size of $target"; return 1; }
+    size="$_RET"
+    
+    dd if=/dev/zero conv=notrunc of="$target" \
+        bs=$((1024*1024)) count=1 >/dev/null 2>&1 ||
+        { error "failed to zero beginning of $target"; return 1; }
 
-	out=$(dd if=/dev/zero conv=notrunc of="$target" bs=1024 \
-		seek=$(((size/1024)-1024)) count=1024 2>&1)
-	[ $? -eq 0 ] ||
-		{ error "failed to wipe end of $target [$size]: $out"; return 1; }
+    out=$(dd if=/dev/zero conv=notrunc of="$target" bs=1024 \
+        seek=$(((size/1024)-1024)) count=1024 2>&1)
+    [ $? -eq 0 ] ||
+        { error "failed to wipe end of $target [$size]: $out"; return 1; }
 
     if [ -b "$target" ]; then
-	    blockdev --rereadpt "$target"
-	    udevadm settle
+        blockdev --rereadpt "$target"
+        udevadm settle
     fi
 }
 
@@ -69,132 +69,132 @@ pt_gpt() {
 
 
 pt_mbr() {
-	local target="$1" end=${2:-""} size="" s512="" ptype="L"
-	local start="2048" pt1size="" maxsize="4294967296"
-	local isblk=false
-	getsize "$target" ||
-		{ error "failed to get size of $target"; return 1; }
-	size="$_RET"
+    local target="$1" end=${2:-""} size="" s512="" ptype="L"
+    local start="2048" pt1size="" maxsize="4294967296"
+    local isblk=false
+    getsize "$target" ||
+        { error "failed to get size of $target"; return 1; }
+    size="$_RET"
 
-	if [ "$(($size/512))" -gt "$maxsize" ]; then
-		debug 1 "disk is larger than max for mbr (2TB)"
-		s512=$maxsize
-	else
-		s512=$(($size/512))
-	fi
-	if [ -n "$end" ]; then
-		pt1size=$(((end/512)-2048))
-	else
-		pt1size=$((s512-2048))
-	fi
+    if [ "$(($size/512))" -gt "$maxsize" ]; then
+        debug 1 "disk is larger than max for mbr (2TB)"
+        s512=$maxsize
+    else
+        s512=$(($size/512))
+    fi
+    if [ -n "$end" ]; then
+        pt1size=$(((end/512)-2048))
+    else
+        pt1size=$((s512-2048))
+    fi
 
-	[ -b "$target" ] && isblk=true
+    [ -b "$target" ] && isblk=true
 
-	# interact with sfdisk in units of 512 bytes (--unit S)
-	# we start all partitions at 2048 of those (1M)
-	local sfdisk_out="" sfdisk_in="2048,$pt1size,$ptype,*" sfdisk_cmd=""
-	sfdisk_cmd=( sfdisk --no-reread --force --Linux --unit S "$target" )
-	debug 1 "sfdisking with: echo '$sfdisk_in' | ${sfdisk_cmd[*]}"
-	sfdisk_out=$(echo "$sfdisk_in" | "${sfdisk_cmd[@]}" 2>&1)
-	ret=$?
-	[ $ret -eq 0 ] || {
-		error "failed to partition $target [${sfdisk_out}]";
-		return 1;
-	}
-	if $isblk; then
-		blockdev --rereadpt "$target"
-		udevadm settle
-		[ -b "${target}1" ] ||
-			{ error "no partition found ${target}1"; return 1; }
-	fi
-	out=$(wipefs "--offset=$(($start*512))" "$target" 2>&1) || {
-		error "$out";
-		error "failed to wipefs first partition of $target";
-		return 1;
-	}
+    # interact with sfdisk in units of 512 bytes (--unit S)
+    # we start all partitions at 2048 of those (1M)
+    local sfdisk_out="" sfdisk_in="2048,$pt1size,$ptype,*" sfdisk_cmd=""
+    sfdisk_cmd=( sfdisk --no-reread --force --Linux --unit S "$target" )
+    debug 1 "sfdisking with: echo '$sfdisk_in' | ${sfdisk_cmd[*]}"
+    sfdisk_out=$(echo "$sfdisk_in" | "${sfdisk_cmd[@]}" 2>&1)
+    ret=$?
+    [ $ret -eq 0 ] || {
+        error "failed to partition $target [${sfdisk_out}]";
+        return 1;
+    }
+    if $isblk; then
+        blockdev --rereadpt "$target"
+        udevadm settle
+        [ -b "${target}1" ] ||
+            { error "no partition found ${target}1"; return 1; }
+    fi
+    out=$(wipefs "--offset=$(($start*512))" "$target" 2>&1) || {
+        error "$out";
+        error "failed to wipefs first partition of $target";
+        return 1;
+    }
 }
 
 partition_main() {
-	local short_opts="hE:f:v"
-	local long_opts="help,end:,format:,verbose"
-	local getopt_out=$(getopt --name "${0##*/}" \
-		--options "${short_opts}" --long "${long_opts}" -- "$@") &&
-		eval set -- "${getopt_out}" ||
-		{ partition_usage 1>&2; return 1; }
+    local short_opts="hE:f:v"
+    local long_opts="help,end:,format:,verbose"
+    local getopt_out=$(getopt --name "${0##*/}" \
+        --options "${short_opts}" --long "${long_opts}" -- "$@") &&
+        eval set -- "${getopt_out}" ||
+        { partition_usage 1>&2; return 1; }
 
-	local cur="" next=""
-	local format="mbr" target="" end=""
+    local cur="" next=""
+    local format="mbr" target="" end=""
 
-	while [ $# -ne 0 ]; do
-		cur="$1"; next="$2";
-		case "$cur" in
-			-h|--help) partition_usage ; exit 0;;
-			-f|--format) format=$next; shift;;
-			-E|--end) end=$next; shift;;
-			-v|--verbose) VERBOSITY=$((${VERBOSITY}+1));;
-			--) shift; break;;
-		esac
-		shift;
-	done
+    while [ $# -ne 0 ]; do
+        cur="$1"; next="$2";
+        case "$cur" in
+            -h|--help) partition_usage ; exit 0;;
+            -f|--format) format=$next; shift;;
+            -E|--end) end=$next; shift;;
+            -v|--verbose) VERBOSITY=$((${VERBOSITY}+1));;
+            --) shift; break;;
+        esac
+        shift;
+    done
 
-	[ $# -gt 1 ] && { partition_usage "got $# args, expected 1" 1>&2; return 1; }
-	[ $# -eq 0 ] && { partition_usage "must provide target-dev" 1>&2; return 1; }
-	target="$1"
-	if [ -n "$end" ]; then
-		human2bytes "$end" ||
-			{ error "failed to convert '$end' to bytes"; return 1; }
-		end="$_RET"
-	fi
+    [ $# -gt 1 ] && { partition_usage "got $# args, expected 1" 1>&2; return 1; }
+    [ $# -eq 0 ] && { partition_usage "must provide target-dev" 1>&2; return 1; }
+    target="$1"
+    if [ -n "$end" ]; then
+        human2bytes "$end" ||
+            { error "failed to convert '$end' to bytes"; return 1; }
+        end="$_RET"
+    fi
 
-	[ "$format" = "gpt" -o "$format" = "mbr" ] ||
-		{ partition_usage "invalid format: $format" 1>&2; return 1; }
+    [ "$format" = "gpt" -o "$format" = "mbr" ] ||
+        { partition_usage "invalid format: $format" 1>&2; return 1; }
 
-	TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") ||
-		fail "failed to make tempdir"
+    TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") ||
+        fail "failed to make tempdir"
 
-	[ -e "$target" ] || { error "$target does not exist"; return 1; }
-	[ -f "$target" -o -b "$target" ] ||
-		{ error "$target not a block device"; return 1; }
+    [ -e "$target" ] || { error "$target does not exist"; return 1; }
+    [ -f "$target" -o -b "$target" ] ||
+        { error "$target not a block device"; return 1; }
 
-	wipedev "$target" ||
-		{ error "wiping $target failed"; return 1; }
+    wipedev "$target" ||
+        { error "wiping $target failed"; return 1; }
 
-	if [ "$format" = "mbr" ]; then
-		pt_mbr "$target" "$end"
-	elif [ "$format" = "gpt" ]; then
-		pt_gpt "$target" "$end"
-	fi
+    if [ "$format" = "mbr" ]; then
+        pt_mbr "$target" "$end"
+    elif [ "$format" = "gpt" ]; then
+        pt_gpt "$target" "$end"
+    fi
 
-	trap cleanup EXIT
+    trap cleanup EXIT
 
-	return 0
+    return 0
 }
 
 human2bytes() {
-	# converts size suitable for input to resize2fs to bytes
-	# s:512 byte sectors, K:kilobytes, M:megabytes, G:gigabytes
-	# none: block size of the image
-	local input=${1} defunit=${2:-1024}
-	local unit count;
-	case "$input" in
-		*s) count=${input%s}; unit=512;;
-		*K) count=${input%K}; unit=1024;;
-		*M) count=${input%M}; unit=$((1024*1024));;
-		*G) count=${input%G}; unit=$((1024*1024*1024));;
-		*)  count=${input}  ; unit=${defunit};;
-	esac
+    # converts size suitable for input to resize2fs to bytes
+    # s:512 byte sectors, K:kilobytes, M:megabytes, G:gigabytes
+    # none: block size of the image
+    local input=${1} defunit=${2:-1024}
+    local unit count;
+    case "$input" in
+        *s) count=${input%s}; unit=512;;
+        *K) count=${input%K}; unit=1024;;
+        *M) count=${input%M}; unit=$((1024*1024));;
+        *G) count=${input%G}; unit=$((1024*1024*1024));;
+        *)  count=${input}  ; unit=${defunit};;
+    esac
    _RET=$((${count}*${unit}))
 }
 
 getsize() {
-	local target="$1"
-	if [ -b "$target" ]; then
-		_RET=$(blockdev --getsize64 "$target")
-	elif [ -f "$target" ]; then
-		_RET=$(stat "--format=%s" "$target")
-	else
-		return 1;
-	fi
+    local target="$1"
+    if [ -b "$target" ]; then
+        _RET=$(blockdev --getsize64 "$target")
+    elif [ -f "$target" ]; then
+        _RET=$(stat "--format=%s" "$target")
+    else
+        return 1;
+    fi
 }
 
 is_md() {
