Fix tab-spacing issue in helpers/common. Made has_pkg_available use splitlines, not to select subpacakges.
bzr-revno: 121.1.4

diff --git a/helpers/common b/helpers/common
--- a/helpers/common
+++ b/helpers/common
@@ -12,11 +12,11 @@ Usage: ${0##*/} [ options ] target-dev
    destroy any partition table that might be there already.
 
    options:
-     -f | --format F   use partition table format F. [mbr, gpt, uefi]
-                       default gpt
-     -E | --end E      end the partition at E (unit 1k bytes)
+	 -f | --format F   use partition table format F. [mbr, gpt, uefi]
+					   default gpt
+	 -E | --end E      end the partition at E (unit 1k bytes)
 EOF
-    [ $# -eq 0 ] || echo "$@"
+	[ $# -eq 0 ] || echo "$@"
 }
 
 grub_install_usage() {
@@ -26,15 +26,15 @@ Usage: ${0##*/} [ options ] mount-point target-dev
    perform grub-install with mount-point onto target-dev.
 
    options:
-          --uefi       install grub-efi instead of grub-pc
+		  --uefi       install grub-efi instead of grub-pc
 EOF
-    [ $# -eq 0 ] || echo "$@"
+	[ $# -eq 0 ] || echo "$@"
 }
 
 cleanup() {
-    if [ -d "$TEMP_D" ]; then
-        rm -Rf "$TEMP_D"
-    fi
+	if [ -d "$TEMP_D" ]; then
+		rm -Rf "$TEMP_D"
+	fi
 }
 
 wipedev() {
@@ -53,31 +53,31 @@ wipedev() {
 	[ $? -eq 0 ] ||
 		{ error "failed to wipe end of $target [$size]: $out"; return 1; }
 
-    if [ -b "$target" ]; then
-	    blockdev --rereadpt "$target"
-	    udevadm settle
-    fi
+	if [ -b "$target" ]; then
+		blockdev --rereadpt "$target"
+		udevadm settle
+	fi
 }
 
 pt_gpt() {
-    local target="$1" end=${2:-""} size="" s512="" ptype="L"
-    local start="2048" pt1size="" maxend=""
-    local isblk=false
-    getsize "$target" ||
-        { error "failed to get size of $target"; return 1; }
-    size="$_RET"
-    if [ -z "$end" ]; then
-        end=$(($size/512))
-    else
-        end=$(($end/512))
-    fi
-    maxend=$((($size/512)-2048))
-    [ "$end" -gt "$maxend" ] && end="$maxend"
-    debug 1 "maxend=$maxend end=$end size=$size"
+	local target="$1" end=${2:-""} size="" s512="" ptype="L"
+	local start="2048" pt1size="" maxend=""
+	local isblk=false
+	getsize "$target" ||
+		{ error "failed to get size of $target"; return 1; }
+	size="$_RET"
+	if [ -z "$end" ]; then
+		end=$(($size/512))
+	else
+		end=$(($end/512))
+	fi
+	maxend=$((($size/512)-2048))
+	[ "$end" -gt "$maxend" ] && end="$maxend"
+	debug 1 "maxend=$maxend end=$end size=$size"
 
-    sgdisk --new "15:2048:+1M" --typecode=15:ef02 \
-           --new "1::$end"     --typecode=1:8300 "$target"
-    ret=$?
+	sgdisk --new "15:2048:+1M" --typecode=15:ef02 \
+		   --new "1::$end"     --typecode=1:8300 "$target"
+	ret=$?
 
 	if $isblk; then
 		blockdev --rereadpt "$target"
@@ -90,25 +90,25 @@ pt_gpt() {
 }
 
 pt_uefi() {
-    local target="$1" end=${2:-""} size="" s512="" ptype="L"
-    local start="2048" pt1size="" maxend=""
-    local isblk=false
-    getsize "$target" ||
-        { error "failed to get size of $target"; return 1; }
-    size="$_RET"
-    if [ -z "$end" ]; then
-        end=$(($size/512))
-    else
-        end=$(($end/512))
-    fi
-    maxend=$((($size/512)-2048))
-    [ "$end" -gt "$maxend" ] && end="$maxend"
-    debug 1 "maxend=$maxend end=$end size=$size"
+	local target="$1" end=${2:-""} size="" s512="" ptype="L"
+	local start="2048" pt1size="" maxend=""
+	local isblk=false
+	getsize "$target" ||
+		{ error "failed to get size of $target"; return 1; }
+	size="$_RET"
+	if [ -z "$end" ]; then
+		end=$(($size/512))
+	else
+		end=$(($end/512))
+	fi
+	maxend=$((($size/512)-2048))
+	[ "$end" -gt "$maxend" ] && end="$maxend"
+	debug 1 "maxend=$maxend end=$end size=$size"
 
-    # Part 15 is the UEFI partition, part 1 is root
-    sgdisk --new "15:2048:+100M" --typecode=15:ef00 "$target" \
-           --new "1::$end" --typecode=1:8300 "$target"
-    ret=$?
+	# Part 15 is the UEFI partition, part 1 is root
+	sgdisk --new "15:2048:+100M" --typecode=15:ef00 "$target" \
+		   --new "1::$end" --typecode=1:8300 "$target"
+	ret=$?
 
 	if $isblk; then
 		blockdev --rereadpt "$target"
@@ -119,8 +119,8 @@ pt_uefi() {
 			{ error "no partition found ${target}15"; return 1; }
 	fi
 
-    mkfs -t vfat -F 32 -n uefi-boot ${target}15 ||
-        { error "failed to partition ${target}15 for UEFI vfat"; return 1; }
+	mkfs -t vfat -F 32 -n uefi-boot ${target}15 ||
+		{ error "failed to partition ${target}15 for UEFI vfat"; return 1; }
 }
 
 
@@ -245,192 +245,192 @@ human2bytes() {
 }
 
 getsize() {
-    local target="$1"
-    if [ -b "$target" ]; then
-        _RET=$(blockdev --getsize64 "$target")
-    elif [ -f "$target" ]; then
-        _RET=$(stat "--format=%s" "$target")
-    else
-        return 1;
-    fi
+	local target="$1"
+	if [ -b "$target" ]; then
+		_RET=$(blockdev --getsize64 "$target")
+	elif [ -f "$target" ]; then
+		_RET=$(stat "--format=%s" "$target")
+	else
+		return 1;
+	fi
 }
 
 is_md() {
-    case "${1##*/}" in
-        md[0-9]) return 0;;
-    esac
-    return 1
+	case "${1##*/}" in
+		md[0-9]) return 0;;
+	esac
+	return 1
 }
 
 install_grub() {
-    local long_opts="uefi"
-    local getopt_out=$(getopt --name "${0##*/}" \
-        --options "" --long "${long_opts}" -- "$@") &&
-        eval set -- "${getopt_out}"
+	local long_opts="uefi"
+	local getopt_out=$(getopt --name "${0##*/}" \
+		--options "" --long "${long_opts}" -- "$@") &&
+		eval set -- "${getopt_out}"
 
-    local uefi=0
+	local uefi=0
 
-    while [ $# -ne 0 ]; do
-        cur="$1"; next="$2";
-        case "$cur" in
-            --uefi) uefi=$((${uefi}+1));;
-            --) shift; break;;
-        esac
-        shift;
-    done
+	while [ $# -ne 0 ]; do
+		cur="$1"; next="$2";
+		case "$cur" in
+			--uefi) uefi=$((${uefi}+1));;
+			--) shift; break;;
+		esac
+		shift;
+	done
 
-    [ $# -lt 2 ] && { grub_install_usage "must provide mount-point and target-dev" 1>&2; return 1; }
+	[ $# -lt 2 ] && { grub_install_usage "must provide mount-point and target-dev" 1>&2; return 1; }
 
-    local mp="$1"
-    local cmdline tmp r=""
-    shift
-    local grubdevs
-    grubdevs=( "$@" )
+	local mp="$1"
+	local cmdline tmp r=""
+	shift
+	local grubdevs
+	grubdevs=( "$@" )
 
-    # find the mp device
-    mp_dev=$(awk -v MP=${mp} '$2==MP {print$1}' /proc/mounts)
-    r=$?
-    if [ $r -ne 0 -a $r -ne 1 ]; then
-        error "unable to determine device for mount $mp";
-        return 1;
-    fi
-    [ -b $mp_dev ] || { error "$mp_dev is not a block device!"; return 1; }
+	# find the mp device
+	mp_dev=$(awk -v MP=${mp} '$2==MP {print$1}' /proc/mounts)
+	r=$?
+	if [ $r -ne 0 -a $r -ne 1 ]; then
+		error "unable to determine device for mount $mp";
+		return 1;
+	fi
+	[ -b $mp_dev ] || { error "$mp_dev is not a block device!"; return 1; }
 
-    # set correct grub package
-    local grub_name="grub-pc"
-    local grub_target="i386-pc"
-    if [ "$uefi" -ge 1 ]; then
-    	dpkg_arch=$(chroot "$mp" dpkg --print-architecture)
-        r=$?
-        if [ $r -ne 0 -a $r -ne 1 ]; then
-            error "failed to get dpkg architecture"
-            return 1;
-        fi
-        grub_name="grub-efi-$dpkg_arch"
-        if [ "$dpkg_arch" = "amd64" ]; then
-        	grub_target="x86_64-efi"
-        fi
-    fi
+	# set correct grub package
+	local grub_name="grub-pc"
+	local grub_target="i386-pc"
+	if [ "$uefi" -ge 1 ]; then
+		dpkg_arch=$(chroot "$mp" dpkg --print-architecture)
+		r=$?
+		if [ $r -ne 0 -a $r -ne 1 ]; then
+			error "failed to get dpkg architecture"
+			return 1;
+		fi
+		grub_name="grub-efi-$dpkg_arch"
+		if [ "$dpkg_arch" = "amd64" ]; then
+			grub_target="x86_64-efi"
+		fi
+	fi
 
-    # check that the grub package is installed
-    tmp=$(chroot "$mp" dpkg-query --show \
-        --showformat='${Status}\n' $grub_name)
-    r=$?
-    if [ $r -ne 0 -a $r -ne 1 ]; then
-        error "failed to check if $grub_name installed";
-        return 1;
-    fi
-    case "$tmp" in
-        install\ ok\ installed) :;;
-        *) debug 1 "$grub_name not installed, not doing anything";
-            return 0;;
-    esac
+	# check that the grub package is installed
+	tmp=$(chroot "$mp" dpkg-query --show \
+		--showformat='${Status}\n' $grub_name)
+	r=$?
+	if [ $r -ne 0 -a $r -ne 1 ]; then
+		error "failed to check if $grub_name installed";
+		return 1;
+	fi
+	case "$tmp" in
+		install\ ok\ installed) :;;
+		*) debug 1 "$grub_name not installed, not doing anything";
+			return 0;;
+	esac
 
-    # check that mount point has efi partition, and that its mounted
-    # at /boot/efi and added to the fstab
-    if [ "$uefi" -ge 1 ]; then
-    	local efi_dev=${mp_dev:0:8}15
-    	[ -b ${efi_dev} ] || { error "no UEFI partition on ${mp_dev:0:8}"; return 1; }
+	# check that mount point has efi partition, and that its mounted
+	# at /boot/efi and added to the fstab
+	if [ "$uefi" -ge 1 ]; then
+		local efi_dev=${mp_dev:0:8}15
+		[ -b ${efi_dev} ] || { error "no UEFI partition on ${mp_dev:0:8}"; return 1; }
 
-    	fslabel=$(blkid -s LABEL -o value ${efi_dev})
-        fstype=$(blkid -s TYPE -o value ${efi_dev})
-        [ "$fstype" = "vfat" ] || { error "${efi_dev} is not a vfat fs"; return 1; }
-        [ -n "$fslabel" ] || {  error "no label on EFI device"; return 1; }
+		fslabel=$(blkid -s LABEL -o value ${efi_dev})
+		fstype=$(blkid -s TYPE -o value ${efi_dev})
+		[ "$fstype" = "vfat" ] || { error "${efi_dev} is not a vfat fs"; return 1; }
+		[ -n "$fslabel" ] || {  error "no label on EFI device"; return 1; }
 
-        local mp_efi=$(lsblk --nodeps -n --out "MOUNTPOINT" ${efi_dev})
-        [ -z "$mp_efi" ] || umount "$mp_efi"
+		local mp_efi=$(lsblk --nodeps -n --out "MOUNTPOINT" ${efi_dev})
+		[ -z "$mp_efi" ] || umount "$mp_efi"
 
-        if [ ! -e "$mp/boot/efi" ]; then
-            mkdir -p "$mp/boot/efi" || { error "failed to mount EFI partition"; return 1; }
-            mount "$efi_dev" "$mp/boot/efi" || { error "unable to mount efi part"; return 1; }
-            mp_efi="$mp/boot/efi"
-        fi
+		if [ ! -e "$mp/boot/efi" ]; then
+			mkdir -p "$mp/boot/efi" || { error "failed to mount EFI partition"; return 1; }
+			mount "$efi_dev" "$mp/boot/efi" || { error "unable to mount efi part"; return 1; }
+			mp_efi="$mp/boot/efi"
+		fi
 
-        echo "LABEL=${fslabel}  /boot/efi   vfat    defaults    0 0" >> "$mp/etc/fstab"
-    fi
+		echo "LABEL=${fslabel}  /boot/efi   vfat    defaults    0 0" >> "$mp/etc/fstab"
+	fi
 
-    # copy anything after '--' on cmdline to install'd cmdline
-    read cmdline < /proc/cmdline
-    local reconf="" newargs=""
+	# copy anything after '--' on cmdline to install'd cmdline
+	read cmdline < /proc/cmdline
+	local reconf="" newargs=""
 
-    tmp="${cmdline##* -- }"
-    if [ "$tmp" != "$cmdline" ]; then
-        # there was an explicit '--', so copy stuff some after it
-        newargs=$(set -f;
-            c="";
-            for p in ${cmdline##* -- }; do
-                case "$p" in
-                    (BOOTIF=*|initrd=*|BOOT_IMAGE=*) continue;;
-                esac
-                c="$c $p";
-            done
-            echo "${c# }"
-        )
-    elif [ "${cmdline#* console=}" != "${cmdline}" ]; then
-        # there are 'console=' params, copy those.
-        newargs=$(set -f; c=""; for p in $cmdline; do
-            [ "${p#console}" = "$p" ] || c="$c $p"; done; echo "${c# }")
-    fi
+	tmp="${cmdline##* -- }"
+	if [ "$tmp" != "$cmdline" ]; then
+		# there was an explicit '--', so copy stuff some after it
+		newargs=$(set -f;
+			c="";
+			for p in ${cmdline##* -- }; do
+				case "$p" in
+					(BOOTIF=*|initrd=*|BOOT_IMAGE=*) continue;;
+				esac
+				c="$c $p";
+			done
+			echo "${c# }"
+		)
+	elif [ "${cmdline#* console=}" != "${cmdline}" ]; then
+		# there are 'console=' params, copy those.
+		newargs=$(set -f; c=""; for p in $cmdline; do
+			[ "${p#console}" = "$p" ] || c="$c $p"; done; echo "${c# }")
+	fi
 
-    if [ "${REPLACE_GRUB_LINUX_DEFAULT:-1}" != "0" ]; then
-        local n="GRUB_CMDLINE_LINUX_DEFAULT"
-        local sede="s|$n=.*|$n=\"$newargs\"|"
-        sed -i "$sede" "$mp/etc/default/grub" ||
-            { error "failed to update /etc/default/grub"; return 1; }
-        grep "$n" "$mp/etc/default/grub"
-        reconf="dpkg-reconfigure $grub_name"
-        debug 1 "updating cmdline to '${newargs}'"
+	if [ "${REPLACE_GRUB_LINUX_DEFAULT:-1}" != "0" ]; then
+		local n="GRUB_CMDLINE_LINUX_DEFAULT"
+		local sede="s|$n=.*|$n=\"$newargs\"|"
+		sed -i "$sede" "$mp/etc/default/grub" ||
+			{ error "failed to update /etc/default/grub"; return 1; }
+		grep "$n" "$mp/etc/default/grub"
+		reconf="dpkg-reconfigure $grub_name"
+		debug 1 "updating cmdline to '${newargs}'"
 
-        # LP: #1179940 . this fix was applied to raring, which
-        # made changes above not stick.  This might not be the best
-        # way to handle this, but we'll do it for now.
-        local cicfg="etc/default/grub.d/50-cloudimg-settings.cfg"
-        if [ -f "$mp/$cicfg" ]; then
-            debug 1 "moved $cicfg out of the way"
-            mv "$mp/$cicfg" "$mp/$cicfg.disabled"
-        fi
-    fi
+		# LP: #1179940 . this fix was applied to raring, which
+		# made changes above not stick.  This might not be the best
+		# way to handle this, but we'll do it for now.
+		local cicfg="etc/default/grub.d/50-cloudimg-settings.cfg"
+		if [ -f "$mp/$cicfg" ]; then
+			debug 1 "moved $cicfg out of the way"
+			mv "$mp/$cicfg" "$mp/$cicfg.disabled"
+		fi
+	fi
 
-    local short="" bd="" grubdev grubdevs_new=""
-    grubdevs_new=()
-    for grubdev in "${grubdevs[@]}"; do
-        if is_md "$grubdev"; then
-            short=${grubdev##*/}
-            for bd in "/sys/block/$short/slaves/"/*; do
-                [ -d "$bd" ] || continue
-                bd=${bd##*/}
-                bd="/dev/${bd%[0-9]}" # hack: part2bd
-                grubdevs_new[${#grubdevs_new[@]}]="$bd"
-            done
-        else
-            grubdevs_new[${#grubdevs_new[@]}]="$grubdev"
-        fi
-    done
-    grubdevs=( "${grubdevs_new[@]}" )
+	local short="" bd="" grubdev grubdevs_new=""
+	grubdevs_new=()
+	for grubdev in "${grubdevs[@]}"; do
+		if is_md "$grubdev"; then
+			short=${grubdev##*/}
+			for bd in "/sys/block/$short/slaves/"/*; do
+				[ -d "$bd" ] || continue
+				bd=${bd##*/}
+				bd="/dev/${bd%[0-9]}" # hack: part2bd
+				grubdevs_new[${#grubdevs_new[@]}]="$bd"
+			done
+		else
+			grubdevs_new[${#grubdevs_new[@]}]="$grubdev"
+		fi
+	done
+	grubdevs=( "${grubdevs_new[@]}" )
 
-    if [ "$uefi" -ge 1 ]; then
-        debug 1 "installing ${grub_name} to: /boot/efi"
-        chroot "$mp" env DEBIAN_FRONTEND=noninteractive sh -ec '
-            prober="/etc/grub.d/30_os-prober"
-            [ -x $prober ] && chmod -x "$prober"
-            dpkg-reconfigure "$1"
-            [ -f $prober ] && chmod +x "$prober"
-            grub-install --target=$2 --efi-directory=/boot/efi --bootloader-id=ubuntu --recheck || exit; done' \
-            -- "${grub_name}" "${grub_target}" </dev/null ||
-            { error "failed to install grub!"; return 1; }
-    else
-        debug 1 "installing grub-pc to: ${grubdevs[*]}"
-        chroot "$mp" env DEBIAN_FRONTEND=noninteractive sh -ec '
-            prober="/etc/grub.d/30_os-prober"
-            [ -x $prober ] && chmod -x "$prober"
-            dpkg-reconfigure grub-pc
-            [ -f $prober ] && chmod +x "$prober"
-            for d in "$@"; do grub-install "$d" || exit; done' \
-            -- "${grubdevs[@]}" </dev/null ||
-            { error "failed to install grub!"; return 1; }
-    fi
+	if [ "$uefi" -ge 1 ]; then
+		debug 1 "installing ${grub_name} to: /boot/efi"
+		chroot "$mp" env DEBIAN_FRONTEND=noninteractive sh -ec '
+			prober="/etc/grub.d/30_os-prober"
+			[ -x $prober ] && chmod -x "$prober"
+			dpkg-reconfigure "$1"
+			[ -f $prober ] && chmod +x "$prober"
+			grub-install --target=$2 --efi-directory=/boot/efi --bootloader-id=ubuntu --recheck || exit; done' \
+			-- "${grub_name}" "${grub_target}" </dev/null ||
+			{ error "failed to install grub!"; return 1; }
+	else
+		debug 1 "installing grub-pc to: ${grubdevs[*]}"
+		chroot "$mp" env DEBIAN_FRONTEND=noninteractive sh -ec '
+			prober="/etc/grub.d/30_os-prober"
+			[ -x $prober ] && chmod -x "$prober"
+			dpkg-reconfigure grub-pc
+			[ -f $prober ] && chmod +x "$prober"
+			for d in "$@"; do grub-install "$d" || exit; done' \
+			-- "${grubdevs[@]}" </dev/null ||
+			{ error "failed to install grub!"; return 1; }
+	fi
 
-    [ -n "$mp_efi" ] && umount "$mp_efi"
+	[ -n "$mp_efi" ] && umount "$mp_efi"
 }
 
 # vi: ts=4 expandtab syntax=sh
