add and use wipe_partitions, improve wipedev
instead of using sgdisk --zap-all and wipefs, use 'wipedev'.
For partitions, we can now use:
  wipe_partitions /dev/vdb 1

which will wipe the beginning of the partition without
triggering a REREADPT that wipefs would do.

I believe the wipefs call was the reason for the race condition
seen in LP: #1443542.

bzr-revno: 205

diff --git a/helpers/common b/helpers/common
--- a/helpers/common
+++ b/helpers/common
@@ -45,9 +45,27 @@ cleanup() {
     fi
 }
 
+
+wipe_partitions() {
+    # wipe_partition(blockdev, ptno)
+    local dev="$1" target="" ret="" part=""
+    shift
+    for part in "$@"; do
+        find_partno "$dev" $part ||
+            { ret=$?; error "did not find $part on $dev"; return $ret; }
+        target="$_RET"
+        wipedev "$target" false false ||
+            { ret=$?; error "failed to wipe $part on $dev"; return $ret; }
+    done
+    return 0
+}
+
 wipedev() {
-    # wipe the front and end (gpt is at end also)
-    local target="$1" size="" out="" bs="" count="" seek="" mb=$((1024*1024))
+    # wipedev(target, wipe_end=true, reread=true)
+    # wipe the front and optionally end of $target
+    # if reread=true call rereadpt and settle
+    local target="$1" wipe_end=${2:-true} rereadpt=${3:-true}
+    local size="" out="" bs="" count="" seek="" mb=$((1024*1024))
     local info=""
     getsize "$target" ||
         { error "failed to get size of $target"; return 1; }
@@ -72,7 +90,7 @@ wipedev() {
         return 1
     }
 
-    if [ "$size" -gt "$mb" ]; then
+    if $wipe_end && [ "$size" -gt "$mb" ]; then
         # do the last 1MB
         count=$((mb / bs))
         seek=$(((size / bs) - $count))
@@ -87,7 +105,7 @@ wipedev() {
         fi
     fi
 
-    if [ -b "$target" ]; then
+    if $rereadpt && [ -b "$target" ]; then
         blockdev --rereadpt "$target"
         udevadm settle
     fi
@@ -187,6 +205,8 @@ pt_gpt() {
         udevadm settle
         assert_partitions "$target" $expected ||
             { error "$target missing partitions: $_RET"; return 1; }
+        wipe_partitions "$target" $expected ||
+            { error "$target: failed to wipe partitions"; return 1; }
     fi
 }
 
@@ -229,6 +249,8 @@ pt_uefi() {
         udevadm settle
         assert_partitions "$target" 1 15 ||
             { error "$target missing partitions: $_RET"; return 1; }
+        wipe_partitions "$target" 1 15 ||
+            { error "$target: failed to wipe partitions"; return 1; }
     fi
 
     mkfs -t vfat -F 32 -n uefi-boot ${target}15 ||
@@ -240,7 +262,7 @@ pt_mbr() {
     local target="$1" end=${2:-""} boot="$3" size="" s512="" ptype="L"
     local start="2048" rootsize="" maxsize="4294967296"
     local maxend="" isblk=false def_bootsize="1048576" bootsize=0
-    local isblk=false
+    local isblk=false pad
     getsize "$target" ||
         { error "failed to get size of $target"; return 1; }
     size="$_RET"
@@ -286,12 +308,11 @@ pt_mbr() {
         udevadm settle
         assert_partitions "$target" 1 ||
             { error "$target missing partitions: $_RET"; return 1; }
+
+        wipe_partitions "$target" 1 ||
+            { error "failed to wipe partition 1 on $target"; return 1; }
     fi
-    out=$(wipefs "--offset=$(($start*512))" "$target" 2>&1) || {
-        error "$out";
-        error "failed to wipefs first partition of $target";
-        return 1;
-    }
+    
 }
 
 pt_prep() {
@@ -299,7 +320,7 @@ pt_prep() {
     local cmd="" isblk=false
     [ -b "$target" ] && isblk=true
 
-    sgdisk --zap-all "$target" ||
+    wipedev "$target" ||
         { error "failed to clear $target"; return 1; }
 
     cmd=(
@@ -317,11 +338,10 @@ pt_prep() {
     if $isblk; then
         blockdev --rereadpt "$target"
         udevadm settle
-        find_partno "$target" 1 ||
-            { error "$target had no partition 1"; return 1; }
-        dd if=/dev/zero of="$_RET"
-        assert_partitions "$target" 2 ||
+        assert_partitions "$target" 1 2 ||
             { error "$target missing partitions: $_RET"; return 1; }
+        wipe_partitions "$target" 1 2 ||
+            { error "$target: failed to wipe partitions"; return 1;}
     fi
 
     return 0
