Import version 0.1.0~bzr425-0ubuntu1

diff --git a/debian/new-upstream-snapshot b/debian/new-upstream-snapshot
--- a/debian/new-upstream-snapshot
+++ b/debian/new-upstream-snapshot
@@ -20,6 +20,58 @@ EOF
 }
 fail() { echo "$@" 1>&2; exit 1; }
 
+print_commit() {
+    local subject="$1" author="$2" bugs="$3" aname=""
+    aname=${author% <*}
+    echo "    - $subject ${aname:+[${aname}]}${bugs:+ (LP: ${bugs})}"
+}
+
+# unfortunately seems like no easy way to get 'Author' unless
+# the committer sets it on the commit.  And since curtin is doing
+# bzr merge and letting committer merge it, then author doesn't
+# end up correct on most commits.
+#
+# log messages look like:
+#revno: 424 [merge]
+#fixes bug: https://launchpad.net/bugs/1618429
+#committer: Ryan Harper <ryan.harper@canonical.com>
+#branch nick: merge-wesley-lp1618429
+#timestamp: Thu 2016-09-15 08:48:13 -0500
+#message:
+#  block/mdadm: add option to ignore mdadm_assemble errors
+#  
+#  When wiping disks with mdadm partitions we may encounter unexpected
+#  return codes. In the case of wiping disks, we don't care if we 
+#  observe any error so allow wipe to ignore the errors by explicitly
+#  passing in ignore errors.
+bzr_log_to_dch() {
+    local line="" commit="" lcommit="" bugs="" bug=""
+    while :; do
+        read line || break
+        case "$line" in
+            revno:\ *)
+                if [ -n "$commit" ]; then
+                    print_commit "$subject" "$author" "$bugs"
+                fi
+                commit=${line#*: }
+                bugs=""
+                author=""
+                subject=""
+                ;;
+            Author:*) author="${line#Author: }";;
+            fixes\ bug:*)
+                # fixes bug: https://launchpad.net/bugs/1618429
+                bug="#${line##*/}"
+                bugs="${bugs:+${bugs}, }${bug}";;
+            message:)
+                read subject;;
+        esac
+    done
+    if [ -n "$commit" ]; then
+        print_commit "$subject" "$author" "$bugs"
+    fi
+}
+
 [ $# -eq 0 ] && { Usage 1>&2; exit 1; }
 [ "$1" = "-h" -o "$1" = "--help" ] && { Usage; exit 0; }
 trunk=$1
@@ -53,6 +105,7 @@ bzr merge-upstream "$tarball" "--version=${version}" ||
 oldrev=$(($prevno+1))
 ( cd "$trunk" && bzr log -r "${oldrev}..${revno}" ) > new-changes.log ||
    fail "failed to get changes from ${oldrev}..$revno"
+bzr_log_to_dch < new-changes.log > new-dch.log
 
 cat <<EOF
 ====
@@ -60,7 +113,8 @@ Now see ./new-changes.log for changes between $oldrev and $revno
 
 then:
    $ dch --edit
-     # read changes in new-changes.log and write changelog
+     # read changes in new-dch.log or full changes in new-changes.log
+     # and write changelog
    $ debcommit
    $ dch --release
    $ debcommit --release
