add conditional saving of test results and what to save.
Default of CURTIN_VMTEST_KEEP_DATA is now 'fail:all'.  By default,
then all files will be kept if there are failures.  This includes disk
images.

tools/jenkins-runner sets that to 'always:logs'.
This means that jenkins will always keep non-image data, allowing
us to look at output of a good run and a bad run.

bzr-revno: 299.1.28

diff --git a/tools/jenkins-runner b/tools/jenkins-runner
--- a/tools/jenkins-runner
+++ b/tools/jenkins-runner
@@ -1,29 +1,23 @@
 #!/bin/sh
 
+topdir=${CURTIN_VMTEST_TOPDIR:-"${WORKSPACE:-$PWD}/output"}
+export CURTIN_VMTEST_KEEP_DATA=${CURTIN_VMTEST_KEEP_DATA:-"always:logs"}
+export CURTIN_VMTEST_TOPDIR="$topdir"
+export CURTIN_VMTEST_LOG=${CURTIN_VMTEST_LOG:-"$topdir/debug.log"}
+
 fail() { echo "$@" 1>&2; exit 1; }
 
-top_d=${WORKSPACE:-$PWD}
-work_d="${1:-working.d}"
-pub_d=${2:-pub.d}
-
-mkdir -p "$work_d" "$pub_d" || fail "failed to make output dirs"
-work_d=$(cd "$work_d" && pwd) || fail "failed to get pull path to $work_d"
-pub_d=$(cd "$pub_d" && pwd) || fail "failed to get pull path to $pub_d"
-
-keep=${CURTIN_VMTEST_KEEP_DATA:-all}
-log=${CURTIN_VMTEST_LOG:-${work_d}.log}
-
-export CURTIN_VMTEST_KEEP_DATA=${keep}
-export CURTIN_VMTEST_TOPDIR=${work_d}
-export CURTIN_VMTEST_LOG=${log}
+if [ -d "$topdir" ]; then
+    fail "topdir '$topdir' existed."
+fi
+mkdir -p "$topdir" || fail "failed mkdir $topdir"
 
 start_s=$(date +%s)
-make vmtest </dev/null
+echo "$(date -R): vmtest start: nosetests3 $*"
+nosetests3 "$@"
 ret=$?
 end_s=$(date +%s)
-echo "vmtest finished with $ret in $(($end_s-$start_s))s"
+echo "$(date -R): vmtest end [$ret] in $(($end_s-$start_s))s"
+exit $ret
 
-# now find interesting files in $work_d and copy them to pub_d
-rsync -a --exclude "*.img" "$work_d/" "${pub_d}"
-cp "$log" "debug.log"
-rm -Rf "$work_d"
+# vi: ts=4 expandtab
