jenkins-runner: disable the lockfile timeout by default
When CURTIN_VMTEST_IMAGE_LOCK_TIMEOUT is set to a negative integer
disable the lockfile timeout. By default set it to -1 (no timeout).

Rationale: while it is useful to have a timeout, there is no
sensible default. In a run like (parameters omitted):

  $ jenkins-runner &
  $ vmtest-sync-images &
  $ jenkins-runner

the second jenkins-runner will have to wait for the first one to
finish, as it's locked by vmtest-sync-images. A full vmtest run
can take several hours. I easily spotted successful runs that
took more than 16 hours on our Jenkins log. Setting the default
timeout to something like 20 hours should be safe, but I still
don't think it's a good default, as it is too high for all the
cases where only a subset of the tests is being run. The timeout
is too dependent on the hardware, on how busy the server is,
and on the set of tests which is run. No size fits all.

Other minor changes:
 - Force CURTIN_VMTEST_IMAGE_LOCK_TIMEOUT to be an integer
 - Remove unnecessary quotes around fixed strings

diff --git a/tools/jenkins-runner b/tools/jenkins-runner
--- a/tools/jenkins-runner
+++ b/tools/jenkins-runner
@@ -5,7 +5,7 @@ topdir="${CURTIN_VMTEST_TOPDIR:-${WORKSPACE:-$PWD}/output}"
 pkeep=${CURTIN_VMTEST_KEEP_DATA_PASS:-logs,collect}
 fkeep=${CURTIN_VMTEST_KEEP_DATA_FAIL:-logs,collect}
 reuse=${CURTIN_VMTEST_REUSE_TOPDIR:-0}
-ltimeout=${CURTIN_VMTEST_IMAGE_LOCK_TIMEOUT:-3600}
+declare -i ltimeout=${CURTIN_VMTEST_IMAGE_LOCK_TIMEOUT:-"-1"}
 export CURTIN_VMTEST_TAR_DISKS=${CURTIN_VMTEST_TAR_DISKS:-0}
 export CURTIN_VMTEST_REUSE_TOPDIR=$reuse
 export CURTIN_VMTEST_IMAGE_SYNC=${CURTIN_VMTEST_IMAGE_SYNC:-0}
@@ -172,14 +172,20 @@ printf "%.s=" {1..86}; printf "\n\n"
 # like to allow these jobs to not wait behind a pending sync-images; but rather
 # allow it to contend directly with sync-images on the vmtest-images.lock, not
 # running if sync images is active.
-if [ $skip_images_dirlock = "0" ]; then
+declare -a flock_timeout_opts
+ltimeout_msg="no timeout"
+if ((ltimeout >= 0)); then
+    flock_timeout_opts=(--verbose "--timeout=$ltimeout")
+    ltimeout_msg="timeout: ${ltimeout}s"
+fi
+
+if [ $skip_images_dirlock = 0 ]; then
     exec {dirlockfd}< "$IMAGE_DIR"
     if ! flock --nonblock --shared $dirlockfd; then
         # Be more verbose if the lock wasn't acquired immediately
-        error "Acquiring directory lock on $IMAGE_DIR (timeout: ${ltimeout}s)..."
         tlock=$EPOCHSECONDS
-        flock --verbose --timeout="$ltimeout" --shared $dirlockfd > /dev/null ||
-            fail "Failed to acquire the lock."
+        error "Acquiring directory lock on $IMAGE_DIR ($ltimeout_msg)..."
+        flock --shared "${flock_timeout_opts[@]}" $dirlockfd > /dev/null || fail "Failed to acquire the lock."
         tlock=$((EPOCHSECONDS - tlock))
         error "Lock on $IMAGE_DIR acquired after ${tlock}s."
     fi
@@ -191,16 +197,15 @@ fi
 lockfile="$IMAGE_DIR/vmtest-images.lock"
 exec {lockfd}> "$lockfile"
 if ! flock --nonblock --shared $lockfd; then
-    error "Acquiring lock on $lockfile (timeout: ${ltimeout}s)..."
     tlock=$EPOCHSECONDS
-    flock --verbose --timeout="$ltimeout" --shared $lockfd > /dev/null ||
-        fail "Failed to acquire the lock."
+    error "Acquiring lock on $lockfile ($ltimeout_msg)..."
+    flock --shared "${flock_timeout_opts[@]}" $lockfd > /dev/null || fail "Failed to acquire the lock."
     tlock=$((EPOCHSECONDS - tlock))
     error "Lock on $lockfile acquired after ${tlock}s."
 fi
 
 # Close the directory file descriptor (releases the lock too)
-[ $skip_images_dirlock != "0" ] || exec {dirlockfd}>&- || fail "Failed to release lock on $IMAGE_DIR"
+[ $skip_images_dirlock != 0 ] || exec {dirlockfd}>&- || fail "Failed to release lock on $IMAGE_DIR"
 
 echo "$(date -R): vmtest start: nosetests3 ${pargs[*]} ${ntargs[*]}"
 nosetests3 "${pargs[@]}" "${ntargs[@]}"
