Drop control port (IPC socket is sufficient). Update jenkins-runner to spawn tgt in order to test, if it can find IP.
bzr-revno: 450.3.5

diff --git a/tools/jenkins-runner b/tools/jenkins-runner
--- a/tools/jenkins-runner
+++ b/tools/jenkins-runner
@@ -53,6 +53,32 @@ if [ -n "$parallel" -a "$parallel" != "0" -a "$parallel" != "1" ]; then
     pargs=( --process-timeout=86400 "--processes=$parallel" )
 fi
 
+# tgtd/tgtadmin end up using a suffix from here of the control port
+export TGT_IPC_SOCKET=$(mktemp --tmpdir="$topdir")
+IPV4_DEV=$(route -n | grep ^0.0.0.0.*UG | awk '{print $8}')
+if [ -z "$IPV4_DEV" ]; then
+    echo "Unable to find IPV4 device with default gateway, skipping iSCSI tests"
+else
+    IPV4_IP=$(ip addr show dev ${IPV4_DEV} | awk '$1 == "inet" {gsub(/\/.*/,"", $2); print $2; exit}')
+    TGT_PORT=9000
+    while [ 1 == 1 ]; do
+        # Racily try for a port. Annoyingly, tgtd doesn't fail when it's
+        # unable to use the requested portal, it just happily uses the
+        # default
+        export CURTIN_VMTEST_ISCSI_PORTAL_V4=${IPV4_IP}:${TGT_PORT}
+        tgtd --foreground --iscsi portal=${CURTIN_VMTEST_ISCSI_PORTAL_V4} >/dev/null 2>&1 &
+        TGT_PID=$!
+        # did we succesfully attach to the correct port?
+        netstat -pan 2>/dev/null | grep -q "${TGT_PORT}.*tgtd"
+        if [ $? == 0 ]; then
+            break
+        fi
+        read
+        kill -9 "${TGT_PID}"
+        ((TGT_PORT++))
+    done
+fi
+
 # avoid LOG info by running python3 tests/vmtests/image_sync.py
 # rather than python3 -m tests.vmtests.image_sync (LP: #1594465)
 echo "Working with images in $IMAGE_DIR"
@@ -67,6 +93,7 @@ nosetests3 "${pargs[@]}" "${ntargs[@]}"
 ret=$?
 end_s=$(date +%s)
 echo "$(date -R): vmtest end [$ret] in $(($end_s-$start_s))s"
+[ -n "${TGT_PID}" ] && kill -9 ${TGT_PID}
 exit $ret
 
 # vi: ts=4 expandtab syntax=sh
