Address smoser's review comments.
bzr-revno: 450.3.37

diff --git a/tools/launch b/tools/launch
--- a/tools/launch
+++ b/tools/launch
@@ -252,7 +252,6 @@ find_apt_proxy() {
 get_tgt_tid() {
     # retry until we successfully register a tid in tgtadm, return it.
     local target="$1" src="$2" out="" tid="" lun="1" ret=""
-    local user="$3" password="$4" iuser="$5" ipassword="$6"
     while true; do
         # use next target ID
         # this is racy, potentially, but we iterate until it works
@@ -288,51 +287,8 @@ get_tgt_tid() {
             return 1
         }
 
-        if [ -n "$user" ]; then
-            tgtadm --lld=iscsi --mode=account --op=show | grep -q "${user}"
-            if [ $? != 0 ]; then
-                tgtadm --lld=iscsi --mode=account --op=new "--user=${user}" \
-                    "--password=${password}" || {
-                    RC=$?
-                    error "Unable to create TGT user (${user}:${password}): ${RC}"
-                    error "Does a prior config need to be cleaned up?"
-                    return 1
-                }
-            fi 
-            tgtadm --lld=iscsi --mode=account --op=bind "--tid=$tid" \
-                "--user=${user}" || {
-                RC=$?
-                error "Unable to set TGT target ${tid} target auth " \
-                      "user to ${user}: ${RC}."
-                error "Does a prior config need to be cleaned up?"
-                return 1
-            }
-        fi
-
-        if [ -n "$iuser" ]; then
-            tgtadm --lld=iscsi --mode=account --op=show | grep -q "${iuser}"
-            if [ $? != 0 ]; then
-                tgtadm --lld=iscsi --mode=account --op=new "--user=${iuser}" \
-                    "--password=${ipassword}" || {
-                    RC=$?
-                    error "Unable to create TGT user (${iuser}:${ipassword}): ${RC}"
-                    error "Does a prior config need to be cleaned up?"
-                    return 1
-                }
-            fi 
-            tgtadm --lld=iscsi --mode=account --op=bind "--tid=$tid" \
-                "--user=${iuser}" --outgoing || {
-                RC=$?
-                error "Unable to set TGT target ${tid} initiator user " \
-                      "to ${iuser}: ${RC}."
-                error "Does a prior config need to be cleaned up?"
-                return 1
-            }
-        fi
-
         # set all initiators to be able to authenticate
-        tgtadm --lld=iscsi --mode=target --op=bind "--tid=$tid" \
-            -I ALL || {
+        tgtadm --lld=iscsi --mode=target --op=bind "--tid=$tid" -I ALL || {
             error "Unable to set TGT target ${tid} ACL to ALL."
             error "Does a prior config need to be cleaned up?"
             return 1
@@ -341,6 +297,55 @@ get_tgt_tid() {
         _RET="$tid"
         return 0
     done
+}
+
+configure_tgt_auth() {
+    # retry until we successfully register a tid in tgtadm, return it.
+    local tid="$1" user="$2" password="$3" iuser="$4" ipassword="$5"
+
+    if [ -n "$user" ]; then
+        tgtadm --lld=iscsi --mode=account --op=show | grep -q "${user}"
+        if [ $? != 0 ]; then
+            tgtadm --lld=iscsi --mode=account --op=new "--user=${user}" \
+                "--password=${password}" || {
+                RC=$?
+                error "Unable to create TGT user (${user}:${password}): ${RC}"
+                error "Does a prior config need to be cleaned up?"
+                return 1
+            }
+        fi 
+        tgtadm --lld=iscsi --mode=account --op=bind "--tid=$tid" \
+            "--user=${user}" || {
+            RC=$?
+            error "Unable to set TGT target ${tid} target auth " \
+                  "user to ${user}: ${RC}."
+            error "Does a prior config need to be cleaned up?"
+            return 1
+        }
+    fi
+
+    if [ -n "$iuser" ]; then
+        tgtadm --lld=iscsi --mode=account --op=show | grep -q "${iuser}"
+        if [ $? != 0 ]; then
+            tgtadm --lld=iscsi --mode=account --op=new "--user=${iuser}" \
+                "--password=${ipassword}" || {
+                RC=$?
+                error "Unable to create TGT user (${iuser}:${ipassword}): ${RC}"
+                error "Does a prior config need to be cleaned up?"
+                return 1
+            }
+        fi 
+        tgtadm --lld=iscsi --mode=account --op=bind "--tid=$tid" \
+            "--user=${iuser}" --outgoing || {
+            RC=$?
+            error "Unable to set TGT target ${tid} initiator user " \
+                  "to ${iuser}: ${RC}."
+            error "Does a prior config need to be cleaned up?"
+            return 1
+        }
+    fi
+
+    return 0
 }
 
 main() {
@@ -526,9 +531,10 @@ main() {
                       "must be specified for iSCSI disk '$disk'"
                 return 1
             }
-            get_tgt_tid "$target" "$src" "$user" "$password" \
-                "$iuser" "$ipassword" || return
+            get_tgt_tid "$target" "$src" || return
             tid="$_RET"
+            configure_tgt_auth "$tid" "$user" "$password" \
+                "$iuser" "$ipassword" || return
             debug 1 "registered $disk to tgt tid=$tid"
             continue
         fi
